ERR_SIGNUP_EXISTS = "User already exists, please log in!"
ERR_SIGNUP = "There was an error while signing up. Please try again later."
ERR_SIGNUP_VERIFICATION = "There was an error while verifying your account. Please try again later."
ERR_SIGNUP_VERIFICATION_EXPIRED = "The verification token has expired. Please try again."
ERR_LOGIN = "Error! Username or password dont match! Please try again."
ERR_PROFILE_DATA = "No data provided"
ERR_SESSION_EXPIRED = "Session Expired! Please login to continue"
ERR_VERIFICATION_GENERATED = "Verification email has already been generated. Please try again in 2 minutes."
ERR_VERIFICATION_EXISTS = "Email is already verified. No action is needed to verify your account again."
ERR_SIGNUP_INVALID_VERIFICATION = (
    "The verification token does not match your account. Please login & re-verify the account."
)
ERR_EMAIL_NOT_EXISTS = "Email does not exist!"
ERR_RESET_REQ_RAISED = "Error while resetting your password. Please try again."
ERR_SENDING_RESET_OTP = "Error while sending Reset Password OTP. "
ERR_OTP_NOT_MATCHED = "Error! OTP does not match. Please try again."
ERROR_OTP_EXPIRED = "Error! OTP has expired. Please try again. "
ERR_WRONG_PWD = "Error! Wrong Password. Please try again."
ERR_SAME_PWD = "Error! Please try with a new password. "
